<script setup lang="ts">
const members=[
  {name:'Maya Chen',role:'Design Lead',initials:'MC',focus:'Brand & product'},
  {name:'Noah Williams',role:'Engineering',initials:'NW',focus:'Systems & platform'},
  {name:'Ava Patel',role:'Product',initials:'AP',focus:'Strategy & research'},
  {name:'Leo Martin',role:'Operations',initials:'LM',focus:'Growth & operations'}
]
</script>
<template><section class="overflow-hidden rounded-[2rem] border border-slate-200 bg-white text-slate-950 dark:border-slate-800 dark:bg-slate-950 dark:text-white"><div class="grid lg:grid-cols-[.75fr_1.25fr]"><div class="flex flex-col justify-between border-b border-slate-200 p-6 sm:p-10 lg:border-b-0 lg:border-r lg:p-12 dark:border-slate-800"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-slate-500">Team</p><h2 class="mt-4 max-w-md text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Small team. Serious craft.</h2><p class="mt-4 max-w-md text-sm leading-6 text-slate-500 dark:text-slate-400">A compact group of designers, engineers, and operators building thoughtful products from the ground up.</p></div><div class="mt-10 flex items-center gap-3 text-sm font-medium"><span class="grid size-9 place-items-center rounded-full bg-slate-950 text-white dark:bg-white dark:text-slate-950">4</span><span>People, one shared standard.</span></div></div><div class="grid grid-cols-1 sm:grid-cols-2"><article v-for="(member,index) in members" :key="member.name" class="group border-b border-slate-200 p-6 last:border-b-0 sm:p-8 dark:border-slate-800" :class="index % 2 === 0 ? 'sm:border-r' : ''"><div class="flex items-start justify-between gap-4"><div class="grid size-14 place-items-center rounded-2xl bg-slate-100 text-sm font-semibold transition duration-300 group-hover:rounded-full dark:bg-slate-900">{{ member.initials }}</div><span class="text-xs text-slate-400">0{{ index + 1 }}</span></div><h3 class="mt-8 text-base font-semibold">{{ member.name }}</h3><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">{{ member.role }}</p><p class="mt-5 text-xs font-medium uppercase tracking-[.14em] text-slate-400">{{ member.focus }}</p></article></div></div></section></template>
